Repository 20hoibe/stack, pull requests merged in 2018-10, with the labels that each got.

#11 app: replace React
  .babelrc
  .eslintrc
  .gitignore
  assets/placeholder.png
  assets/tray.png
  package-lock.json
  package.json
  public/favicon.ico
  public/manifest.json
  src/App.js
  src/CreateTask.js
  src/ListTask.js
  src/bootstrap.min.css
  src/connect.js
  src/electron.js
  src/index.html
  src/index.js
  src/ipc.js
  src/registerServiceWorker.js
  src/screenshot.html
  src/screenshot.js
Labels: enhancement, improvement

#23 tray: improve ui
  src/electron.js
Labels: improvement

#25 app: window styles
  src/electron.js
Labels: enhancement, improvement

#26 Feature/about window
  AUTHORS
  package-lock.json
  package.json
  src/About.css
  src/About.js
  src/App.js
  src/electron.js
Labels: enhancement

#30 tray: fix inconsistency 'Show current Task'
  src/electron.js
Labels: bug

#31 app: make singleton
  src/electron.js
Labels: improvement
